language: node_js
node_js:
  - 15
cache:
  directories:
    - "node_modules"

addons:
  sonarcloud:
    organization: "nbrink91"
    token:
      secure: $SONARCLOUD_ENCRYPTED_TOKEN

install:
  - npm i -g yarn
  - yarn install

script:
  - sonar-scanner

deploy:
  provider: npm
  email: nbrink7@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master