language: node_js
node_js:
  - 15
cache:
  directories:
    - "node_modules"
install:
  - npm i -g yarn
  - yarn install
  - yarn test
deploy:
  provider: npm
  email: nbrink7@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master